{% set name = "typedframe" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/typedframe-{{ version }}.tar.gz
  sha256: d77c12369a0954a305f2e912c433367235d36c61d2f3b37090a8ad6ec4285443

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - numpy
    - pandas
    - python >={{ python_min }}

test:
  imports:
    - typedframe
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/areshytko/typedframe
  summary: Typed Wrappers over Pandas DataFrames with schema validation
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gabrielcnr
